# Generated by Django 5.2.5 on 2025-09-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_assigned_to_alter_task_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('hod', 'Head of Department'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
